Site.create_with(last_success: DateTime.commercial(2013)).find_or_create_by(id: 1, name: "Daily Tee Reminder")
Site.create_with(last_success: DateTime.commercial(2013)).find_or_create_by(id: 2, name: "Shirt Woot")
Site.create_with(last_success: DateTime.commercial(2013)).find_or_create_by(id: 3, name: "TeeFury")
Site.create_with(last_success: DateTime.commercial(2013)).find_or_create_by(id: 4, name: "Ript Apparel")
Site.create_with(last_success: DateTime.commercial(2013)).find_or_create_by(id: 5, name: "The YeTee")
Site.create_with(last_success: DateTime.commercial(2013)).find_or_create_by(id: 6, name: "Qwertee")
Site.create_with(last_success: DateTime.commercial(2013)).find_or_create_by(id: 7, name: "Design By Humans")
Site.create_with(last_success: DateTime.commercial(2013)).find_or_create_by(id: 8, name: "Other Tees")